![Ironhack logo](https://i.imgur.com/1QgrNNw.png)

# Lab | Numpy

## Introduction

An important ability of a data scientist/data engineer is to know where and how to find information that helps you to accomplish your work. In the exercise, you will both practice the Numpy features we discussed in the lesson and learn new features by looking up documentations and references.

## Getting Started
There are a bunch of comments which instruct what you are supposed to do step by step. Follow the order of the instructions from top to bottom. Read each instruction carefully and provide your answer beneath it. You should also test your answers to make sure your responses are correct. If one of your responses is incorrect, you may not be able to proceed because later responses may depend upon previous responses.


## Resources

Some of the questions in the assignment are not covered in our lesson. You will learn how to efficiently look up the information on your own. Below are some resources you can find the information you need.

[Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

[Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)

[Google Search](https://www.google.com/search?q=how+to+use+numpy)



# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
np.__version__

'1.22.1'

#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.

**Example of output**:
````python
[[[0.29932768, 0.85812686, 0.75266145, 0.09278988, 0.78358352],
  [0.13437453, 0.65695946, 0.82047594, 0.09764179, 0.52230096]],
 
 [[0.54248247, 0.06431281, 0.65902257, 0.92736679, 0.3302839 ],
  [0.86867236, 0.33960592, 0.62295821, 0.74563567, 0.24351584]],
 
 [[0.21276812, 0.06917533, 0.35106591, 0.82273425, 0.7910178 ],
  [0.37768961, 0.56107736, 0.99965953, 0.97615549, 0.2445537 ]]]
````

In [12]:
# your code here
a = np.random.random(size=(3,2,5))

#### 4. Print *a*.


In [13]:
# your code here
print(a)

[[[0.75771194 0.69673704 0.08818101 0.40455061 0.56571114]
  [0.75500014 0.00922704 0.34247103 0.88609955 0.28616682]]

 [[0.64783594 0.44615226 0.59937879 0.98279817 0.69859334]
  [0.330448   0.95818135 0.24844017 0.85124708 0.48558873]]

 [[0.98035738 0.25561554 0.87425701 0.27670314 0.11992291]
  [0.25453524 0.51237104 0.29652189 0.4476769  0.59773214]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

Expected output:

````python
      [[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]]
````

In [54]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [55]:
# your code here
#b = b.astype(int)
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [56]:
# your code here
#print(a.size)
#print(b.size)
if a.size == b.size:
    print(f"a and b have the same size")
else:
    print(f"a and b does not have the same size")

a and b have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [57]:
# your answer here
#c = a + b

#You can't add a and b because they have different shapes
#
#Possible solution would be:
b = b.reshape((a.shape))

c = a + b

print(c)


[[[1.75771194 1.69673704 1.08818101 1.40455061 1.56571114]
  [1.75500014 1.00922704 1.34247103 1.88609955 1.28616682]]

 [[1.64783594 1.44615226 1.59937879 1.98279817 1.69859334]
  [1.330448   1.95818135 1.24844017 1.85124708 1.48558873]]

 [[1.98035738 1.25561554 1.87425701 1.27670314 1.11992291]
  [1.25453524 1.51237104 1.29652189 1.4476769  1.59773214]]]


#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 3x2x5 array). Assign the reshaped array to variable *c*.
*Hint: The tranpose of 5x2x3 is 3x2x5*

Expected output:

````python
      [[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]]
````

In [58]:
# your code here
c = b.reshape((a.shape))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [59]:
# your code/answer here
d = a + c
print(d)

#Now it works because a and d have the same shape

[[[1.75771194 1.69673704 1.08818101 1.40455061 1.56571114]
  [1.75500014 1.00922704 1.34247103 1.88609955 1.28616682]]

 [[1.64783594 1.44615226 1.59937879 1.98279817 1.69859334]
  [1.330448   1.95818135 1.24844017 1.85124708 1.48558873]]

 [[1.98035738 1.25561554 1.87425701 1.27670314 1.11992291]
  [1.25453524 1.51237104 1.29652189 1.4476769  1.59773214]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [60]:
# your code/answer here
print(a)
print()
print()

print(d)
print()
print()


[[[0.75771194 0.69673704 0.08818101 0.40455061 0.56571114]
  [0.75500014 0.00922704 0.34247103 0.88609955 0.28616682]]

 [[0.64783594 0.44615226 0.59937879 0.98279817 0.69859334]
  [0.330448   0.95818135 0.24844017 0.85124708 0.48558873]]

 [[0.98035738 0.25561554 0.87425701 0.27670314 0.11992291]
  [0.25453524 0.51237104 0.29652189 0.4476769  0.59773214]]]


[[[1.75771194 1.69673704 1.08818101 1.40455061 1.56571114]
  [1.75500014 1.00922704 1.34247103 1.88609955 1.28616682]]

 [[1.64783594 1.44615226 1.59937879 1.98279817 1.69859334]
  [1.330448   1.95818135 1.24844017 1.85124708 1.48558873]]

 [[1.98035738 1.25561554 1.87425701 1.27670314 1.11992291]
  [1.25453524 1.51237104 1.29652189 1.4476769  1.59773214]]]




#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [61]:
# your code here
e = a * c
print(e)

[[[0.75771194 0.69673704 0.08818101 0.40455061 0.56571114]
  [0.75500014 0.00922704 0.34247103 0.88609955 0.28616682]]

 [[0.64783594 0.44615226 0.59937879 0.98279817 0.69859334]
  [0.330448   0.95818135 0.24844017 0.85124708 0.48558873]]

 [[0.98035738 0.25561554 0.87425701 0.27670314 0.11992291]
  [0.25453524 0.51237104 0.29652189 0.4476769  0.59773214]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [62]:
# your code/answer here
print(e == a)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [63]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max,d_min, d_mean)

1.9827981711385947 1.0092270396640728 1.521873778524935
